/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CurrentUser: typeof import('./src/components/_internal/current-user.vue')['default']
    DictTag: typeof import('./src/components/_internal/dict-tag.vue')['default']
    ListActions: typeof import('./src/components/_internal/list-actions.vue')['default']
    Logo: typeof import('./src/components/_internal/logo.vue')['default']
    QueryActions: typeof import('./src/components/_internal/query-actions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/_internal/theme-toggle.vue')['default']
  }
}
